### ISSUE TITLE
Allow instructors to download grading files for an assignment 

### ISSUE THREAD

**Issue by abchilders** [acarteas/autograder#31]
- [x] download a ZIP containing student's files, grouped by student name, and a CSV showing all tests run with results
- [x] make file paths absolute on server end to avoid future issues 
- [x] delete stale files on server before dynamically creating ZIP, to ensure correctness
- [x] delete files sometime after serving them to client, to free up storage space? 
- [x] refactor client-side fetch to API 

Final clean-up:

- [x] delete empty student directories under Student Files if they become empty in the process of removing stale files 
- [x] rename folders by assignment_id AND TIMESTAMP instead of assignment name to prevent issues with overwriting

**Comment by abchilders** [comment]
Re: "refactor client-side fetch to API endpoint"--

Problem: The server dynamically generates a ZIP file and then triggers `res.download` for the client to receive and handle. I don't know whether to implement this using Axios or Fetch API. 

Using Axios (implemented in c52549618fa8d2e4e7cfbb81271cfbe1db22b1e8 ):
- Pros: follows convention of using WebRequest within Assignment.js
- Cons: requires me to add a `config` parameter to GET requests in WebRequest.js and I'm not sure if that's a desired modification 

Using Fetch  (implemented in 1059eab8e2865351024103b9ab8bb53575846cea ):
- Pros: Allows ability to get file without altering WebRequest.js
- Cons: Causes `zipGradingFiles()` to be inconsistent with the rest of the requests to our server in `Assignment.js`

Does it matter either way? @acarteas

**Comment by acarteas** [comment]
Axios / fetch is for REST AJAX calls. Wouldn't you just use a raw anchor
tag for downloads? That way it triggers the browser's download mechanism.
Since it's a binary it shouldn't affect React state.

**Comment by abchilders** [comment]
That works if I hardcode a link directly to the API endpoint. So maybe I fetch the URL to the endpoint from the server, and then render an anchor tag containing that link to the API?

**Comment by acarteas** [comment]
Seems reasonable.

**Comment by abchilders** [comment]
Final clean-up:

- [ ] delete empty student directories under Student Files if they become empty in the process of removing stale files 
- [ ] rename folders by assignment_id instead of assignment name to prevent issues with overwriting
