### ISSUE TITLE
Update react version / npm packages

### ISSUE THREAD

**Issue by acarteas** [acarteas/autograder#34]
Running npm update, I get:

```
found 1666 vulnerabilities (1279 low, 24 moderate, 362 high, 1 critical)
```

Seems like the react build needs to be updated.

**Comment by itravers** [comment]
I've created the [react-update](/acarteas/autograder/tree/react-update) branch to work on this.
It's pulled from the current [master](/acarteas/autograder/tree/master) branch.

**Comment by abchilders** [comment]
Just opened PR #35. There are 308 remaining low severity vulnerabilities, all of which have to do with `jest` using an old version of `minimist`. There is an [advisory ](https://npmjs.com/advisories/1179)for this vulnerability, and the [issue ](https://github.com/facebook/jest/issues/10224)regarding this on jest's repository remains open for now.
