### ISSUE TITLE
Manage test cases within assignments

### ISSUE THREAD

**Issue by abchilders** [acarteas/autograder#36]
Allow instructors for a course to manage test cases for each of the course's assignments:

- [x] Let instructors create test cases from client 
- [x] If the result of running a test with a student's code is creating a new file, this file should be added to the assignment view. 
- [x] Minor enhancement: when reloading test cases (say, after creating a new one), either force the selected test case to be the first one in the list again OR force the displayed test case information to match the one selected. 
- [x] In bulk results view, highlight a test result when the date run of the test result < date that the files were last altered (i.e. if a test result was run before the user's files were last modified) 
    - [x] e1f2485cb900aca6f0c8bdd15477e816df1ccaf5 makes the "existsDateMismatch" endpoint obsolete; remove this endpoint/DB function after client is refactored to accommodate new DB changes
- [x] Have a "run all" button that runs test cases on behalf of all the students. 
    - [x] Can put the "run all" in a for loop with a promise chain: run a, get results from a, run b, get results from b, etc. --> send n requests to server 
- [x] Fix bug where if the current user has course permissions to grade/modify course, but isn't instructor or admin, then the bulk results table is fully populated with all of the current user's results (this is caused by a server-side check in getTestResults() where, if you're not an admin or an instructor, the server returns your own results instead of the ones belonging to the given student)

Preliminary tasks:
- [x] figure out what the client's currently doing; add comments as needed 
- [x] figure out why running tests as a different person (your student) doesn't work and fix it

**Comment by abchilders** [comment]
a07950276ee4e19958bba09ee085b5045503f9e2 changed the "dateMismatch" endpoint, which returned the IDs of all test results that were stale, to "existsDateMismatch," which returns a boolean value indicating if the last test a user ran happened before they last modified their files (i.e. tests were run on old versions of files). 

Problem: I'm not sure if this is consistent with the rest of our API. I think that a GET request should reasonably return more data than just true/false, so having this endpoint return all of a user's test result IDs if they're stale would seem more useful-- but then the question is, what's the use case for a list of test result IDs, all of which are stale? I can't think of any reason that one would need such a list.

**Comment by abchilders** [comment]
@acarteas - a question about parallel compilation: I am trying to allow instructors to re-run tests for users whose test results weren't run with the most recent versions of their files. I find that when I make requests to the /assignment/:assignment_id/compile endpoint in parallel, the output produced is incorrect, because requests made in parallel use the same workspace and stdin gets overwritten. Is this intentional, and should I not be writing such requests in parallel? 

Here's what seems to be happening:
 - Client: makes three requests to this endpoint in parallel:
    1. Run the "Simple Add" test with input "5+3"
    2. Run the "One Negative" test with "3-4"
    3. Run the "Both Negative" test with "-2-11"
- Server: receives these three requests correctly & makes three separate calls to the compiler, which are handled asynchronously:
    - Compiler receives Request 1 and creates data/temp/.../stdin.txt => "5+3"
    - Compiler receives Request 2 and overwrites data/temp/.../stdin.txt => "3-4"
    - Compiler receives Request 3 and overwrites data/temp/.../stdin.txt => "-2-11"
    - Compiler then begins running the code for Request 1 with stdin.txt and outputs "-13"
    - (the same occurs for Requests 2 and 3)
- Database: Logs -13 as the test_result for all 3 of these requests. 
- Server: Returns "-13" as the output for all 3 of these requests. 

I understand that this occurs only when requests are made in parallel for the same user/assignment combination-- so if this is intentional/not worth changing, I can just chain compile requests sequentially for each user and then run all of these chains in parallel. I can provide the code I'm testing and my current database configuration if you want to investigate.

**Comment by acarteas** [comment]
Seems like sequential order makes the most sense.  I probably didn't think
about such a problem when originally written.

--Adam

**Comment by abchilders** [comment]
Thanks. Another question about compilation: the server endpoint for compiling only compiles and runs the code for the user that's logged in-- it seems like an instructor can't run a student's code on their behalf. Again, is this intentional, or could I modify that endpoint to take a user_id as an argument? I would need to do something like that in order to implement a "run all" button for running all students' code at once.

**Comment by acarteas** [comment]
Yes, adding a user_id argument seems like a good idea.  Just be sure to
validate privilege on the back end with IsInstructor or whatever makes the
most sense.

--Adam

**Comment by abchilders** [comment]
Docker question: I'm currently working on the task: " If the result of running a test with a student's code is creating a new file, this file should be added to the assignment view."

Since these new files would exist in the Docker container, and the Docker container is removed immediately after use, I'd have to copy these files to the local filesystem in /data/temp/[assignment_id]/[user_id] before removing the container. But wouldn't this defeat the purpose of running the code in a container in the first place? Or is this okay?

**Comment by acarteas** [comment]
Yes, you'd have to copy any files generated during the processing back out of the docker container.  This doesn't seem like much of a security risk to me.

**Comment by abchilders** [comment]
The main tasks for this issue have been done. I want to clean up some things before I make a pull request: 
- [ ] make the addition of files to the database more efficient by only re-uploading files that were modified when running code 
- [ ] fix a bug where refreshing the assignment page causes the selected user id to be reset to -1, which causes issues with server-side permission checks before compiling code 
- [ ] convert file contents from buffer to string *before* uploading to database on server, not *after* an HTTP GET on client

**Comment by abchilders** [comment]
@acarteas Can I ask for your feedback on the "change how temp workspaces on filesystem are cleaned up" task? 

I noticed that files left in the temp workspace for Docker compilation are never deleted, so I wrote code to delete files after each time code is executed so that a fresh copy of files would be uploaded, in case the user decides to delete some of their assignment files. However, Docker only creates a new image if any file names have been changed, if files have been modified, or if files have been added/deleted. 

So before I implemented file deletion, new Docker images were rarely created for the same user/assignment combo, but files sat around in the temp workspace and didn't get deleted. Now, a new Docker image is now created every time the user wants to compile and run code, but there aren't files sitting around in the local filesystem anymore.

Does it matter to you either way how we choose to work with files in the temp workspace? I'm not familiar enough with any storage restrictions on Docker or on the local filesystem to determine which is more efficient or if it's significant enough to worry about.

**Comment by acarteas** [comment]
Creating a new docker image is somewhat computationally expensive.  I think the cost of extra storage for temp files is worth the tradeoff.  However, you could implement a periodic task on the server that cleans files every week.  That would give us the best of both worlds -- less storage and less CPU overhead.
