### ISSUE TITLE
Refactor REST API

### ISSUE THREAD

**Issue by acarteas** [acarteas/autograder#7]
My REST API isn't very consistent or conforming to REST standards.  Refactor as necessary.

**Comment by abchilders** [comment]
**To do, re: standardizing routes--** 

- In server.js: ``router.get('/course/assignments/**active**/:id', (req, res) => {
const course_id = req.params.id;
db.Courses.assignments(course_id, (result) => {
      res.json({ response: result });
   });
});``
What makes an assignment active? Currently, this just selects all assignments under the given course ID. Is the "assignments" table meant to only hold active assignments? If so, where are past assignments stored, if anywhere?

**Comment by abchilders** [comment]
**To ensure REST compliance:**
- [ ] Make all endpoints accessible from the homepage. 
- [ ] Keep UI consistent throughout 
- [ ] Standardize HTTP verbs in server.js

**Comment by abchilders** [comment]
> **To ensure REST compliance:**
> 
> * [ ]  Make all endpoints accessible from the homepage. (this is a client-side thing)
> * [ ]  Keep UI consistent throughout
> * [ ]  Standardize HTTP verbs in server.js

**Comment by abchilders** [comment]
Today: 
- [ ] finish unfinished functions
- [ ] abstract out contents of server.js
- [ ] front-end: think about what dashboard would look like on the student end (e.g. like Canvas)
- [ ] front-end: have a course selector - change between courses 


If batch file not found when trying to run test cases on client: 
--see compileFiles() and adjust accordingly: https://github.com/acarteas/autograder/blob/master/server/Models/Windows_Metal_MSVC_Compiler.js

**Comment by abchilders** [comment]
**Refactoring:**
- [ ] convert all DB functions using callbacks to Promises 
- [ ] config.js on client-- write helper function to create endpoints (see Google Chat for example)

**Comment by acarteas** [comment]
@abchilders what's the status of this?  I'd like to get your work into the main branch soon.

**Comment by abchilders** [comment]
Still working on test cases, but everything else is ready to merge. I'm not optimistic about finishing enough test cases to be meaningful, but I'm still finishing up my hours outside of class.

**Comment by abchilders** [comment]
I haven't made substantial progress on test cases. Shall I just merge my existing work into the main branch? I'd like to keep working on test cases, but I don't have as much time to work on them currently as I did last month, so progress will be limited.

**Comment by acarteas** [comment]
Yes, prioritize merging over test cases right now.
